person_1 = input("Enter your first person: ")
person_2 = input("Enter your second person: ")
plural_noun = input("Enter a plural noun: ")
person = input("Enter a person: ")
noun = input("Enter a noun: ")
verb = input("Enter a verb: ")
noun_2 = input("Enter a second noun: ")
noun_3 = input("Enter a third noun: ")

print(person_1 + " and " + person_2, " fell in love")
print(plural_noun + " is very beautiful")
print("I love " + person, "so much that I can't hide it")
print("But then I walked down the street and seen a " + noun)
print("They was chasing me and I " + verb)
print("I fell into a " + noun_2)
print("But then I realized it was all a " + noun_3)